#!/usr/bin/env bash
export GATLING_SERVER_URL="${GATLING_SERVER_URL:-http://localhost:58080}"
export GATLING_SERVER_API_TOKEN="${GATLING_SERVER_API_TOKEN:-default}"
export GATLING_MCP_API_TOKEN="${GATLING_MCP_API_TOKEN:-default}"
export GATLING_MCP_REQUEST_TIMEOUT="${GATLING_MCP_REQUEST_TIMEOUT:-30}"
export GATLING_MCP_UPLOAD_TIMEOUT="${GATLING_MCP_UPLOAD_TIMEOUT:-300}"
python3 server.py
